services:
  - type: web
    name: telegram-growth-engine
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    region: oregon
    autoDeploy: true
    branch: main
    envVars:
      - key: BOT_TOKEN
        value: "8196680231:AAER9EAE2l2GAAFdnJ77ROm3K-y4Wf37nwE"
      - key: DATABASE_URL
        value: "postgresql://postgres:Kaushtubh.1@db.yholtsvlkpcxclwecpfu.supabase.co:5432/postgres"
      - key: ADMIN_IDS
        value: "8362763548"
      - key: SUPERADMIN_IDS
        value: "8362763548"
      - key: PORT
        value: "10000"
      - key: LOG_LEVEL
        value: "INFO"
